name: 'SimplicoAI Action TF'
description: 'Run SimplicoAI TF'
inputs:
  github_action_access_token:
    description: 'github token for creating pull request'
    required: true
  github_run_number:
    description: 'github run number'
    required: true
  github_repo_name:
    description: 'github repo name'
    required: true
  branch_name:
    description: 'branch name'
    required: true
  terraform_root_dir:
    description: 'terraform root directory'
    required: true
  openai_api_key:
    description: 'openai api key'
    required: true
  verbose:
    description: 'verbose'
    required: false
    default: 'false'
outputs:
  logs:
    description: "SimplicoAI Action logs"
runs:
    using: 'docker'
    image: 'Dockerfile'
    env:
      TERRAFORM_PATH: ${{ inputs.terraform_root_dir }}
      OPENAI_API_KEY: ${{ inputs.openai_api_key }}
      GITHUB_ACCESS_TOKEN: ${{ inputs.github_action_access_token }}
      GITHUB_RUN_NUMBER: ${{ inputs.github_run_number }}
      REPO_NAME: ${{ inputs.github_repo_name }}
      BRANCH_NAME: ${{ inputs.branch_name }}
      VERBOSE: ${{ inputs.verbose }}
